using FenixLegalOs.Models.Enums;

namespace FenixLegalOs.Models.Report;

/// <summary>
/// Immutable, fully-evaluated deterministic report context generated by ReportEngine.
/// Contains 100% of structured data required to render the 12-page executive report.
/// </summary>
public class ReportContext
{
    public string SessionId { get; set; } = string.Empty;
    public string ReportNumber { get; set; } = string.Empty;
    public string GeneratedDate { get; set; } = DateTime.UtcNow.ToString("dd MMMM yyyy", new System.Globalization.CultureInfo("ru-RU"));
    public string ProjectName { get; set; } = "Стартап";
    public string ProjectStage { get; set; } = "Ранняя стадия";

    public ProjectProfileDto Profile { get; set; } = new();
    public OverallScoreDto Overall { get; set; } = new();
    public string ExecutiveConclusion { get; set; } = string.Empty;
    public List<TopFindingSummaryDto> TopFindings { get; set; } = new();
    public List<RootCauseSummaryDto> RootCauses { get; set; } = new();
    public List<RiskFinding> AllFindings { get; set; } = new();
    public List<PositiveFactorDto> PositiveFactors { get; set; } = new();
    public List<ModuleCardDto> ModuleCards { get; set; } = new();
    public List<FocusModuleDetailDto> FocusModules { get; set; } = new();
    public List<CompactModuleDto> CompactModules { get; set; } = new();
    public List<NotApplicableModuleDto> NotApplicableModules { get; set; } = new();
    public InvestmentReadinessReportDto? InvestmentReadiness { get; set; }
    public List<UnifiedActionItemDto> ActionPlan { get; set; } = new();
    public FenixLawRecommendationReportDto FenixLaw { get; set; } = new();
    public MethodologyAndDisclaimerDto LegalTerms { get; set; } = new();
}

public class RootCauseSummaryDto
{
    public string Code { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string SectionId { get; set; } = string.Empty;
    public RiskSeverity MaxSeverity { get; set; }
    public RiskPriority Priority { get; set; }
    public List<string> FindingCodes { get; set; } = new();
    public string Description { get; set; } = string.Empty;
}

public class ProjectProfileDto
{
    public List<FactItemDto> KeyFacts { get; set; } = new();
    public string ConfigurationNarrative { get; set; } = string.Empty;
}

public class FactItemDto
{
    public string Key { get; set; } = string.Empty;
    public string Label { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
    public string? Icon { get; set; }
}

public class OverallScoreDto
{
    public int Score { get; set; }
    public string Band { get; set; } = string.Empty;
    public string LevelTitle { get; set; } = string.Empty;
    public string LevelText { get; set; } = string.Empty;
    public int Confidence { get; set; }
    public string ConfidenceText { get; set; } = string.Empty;
    public List<string> TopDrivers { get; set; } = new();
    public string BottomExplanation { get; set; } = string.Empty;
}

public class TopFindingSummaryDto
{
    public int Index { get; set; }
    public string FindingCode { get; set; } = string.Empty;
    public string RootCauseCode { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public RiskSeverity Severity { get; set; }
    public string SeverityLabel { get; set; } = string.Empty;
    public string ShortSummary { get; set; } = string.Empty;
    public string DetailSectionId { get; set; } = string.Empty;
}

public class PositiveFactorDto
{
    public string Title { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public string? Icon { get; set; }
}

public enum ReportRenderMode
{
    Focus,
    Compact,
    NotApplicable
}

public class ModuleCardDto
{
    public string SectionId { get; set; } = string.Empty;
    public int Order { get; set; }
    public string Title { get; set; } = string.Empty;
    public int? Score { get; set; }
    public RiskSeverity? MaxSeverity { get; set; }
    public string? MaxSeverityLabel { get; set; }
    public ReportRenderMode RenderMode { get; set; }
    public string StatusText { get; set; } = string.Empty;
    public string? ReasonIfNa { get; set; }
    public string? TriggerIfNa { get; set; }
    public string? Icon { get; set; }
}

public class FocusModuleDetailDto
{
    public string SectionId { get; set; } = string.Empty;
    public int Order { get; set; }
    public string Title { get; set; } = string.Empty;
    public int Score { get; set; }
    public string ScoreBand { get; set; } = string.Empty;
    public RiskSeverity MaxSeverity { get; set; }
    public string MaxSeverityLabel { get; set; } = string.Empty;
    public string SubtitleNarrative { get; set; } = string.Empty;
    public string PracticalMeaning { get; set; } = string.Empty;
    public List<string> NegativeDrivers { get; set; } = new();
    public List<string> AttentionDrivers { get; set; } = new();
    public List<string> PositiveDrivers { get; set; } = new();
    public List<FactorBreakdownRowDto> FactorBreakdown { get; set; } = new();
    public List<ReportFindingCardDto> Findings { get; set; } = new();
}

public class FactorBreakdownRowDto
{
    public string FactorName { get; set; } = string.Empty;
    public string StatusText { get; set; } = string.Empty;
    public string ImpactLevel { get; set; } = "Среднее"; // Высокое, Среднее, Низкое, Положительное
    public RiskSeverity? Severity { get; set; }
    public bool IsPositive { get; set; }
}

public class ReportFindingCardDto
{
    public string FindingCode { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public RiskSeverity Severity { get; set; }
    public string SeverityLabel { get; set; } = string.Empty;
    public string WhyFound { get; set; } = string.Empty;
    public string WhyItMatters { get; set; } = string.Empty;
    public string Recommendation { get; set; } = string.Empty;
    public RiskPriority Priority { get; set; }
    public string PriorityLabel { get; set; } = string.Empty;
    public string ResolutionFormat { get; set; } = "Желательно проверить с юристом";
}

public class CompactModuleDto
{
    public string SectionId { get; set; } = string.Empty;
    public int Order { get; set; }
    public string Title { get; set; } = string.Empty;
    public int Score { get; set; }
    public string StatusText { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public List<string> NegativePoints { get; set; } = new();
    public List<string> PositivePoints { get; set; } = new();
}

public class NotApplicableModuleDto
{
    public string SectionId { get; set; } = string.Empty;
    public int Order { get; set; }
    public string Title { get; set; } = string.Empty;
    public string ReasonText { get; set; } = string.Empty;
    public string TriggerEventText { get; set; } = string.Empty;
}

public class InvestmentReadinessReportDto
{
    public bool IsApplicable { get; set; }
    public int ReadinessScore { get; set; }
    public string Category { get; set; } = string.Empty;
    public int BaseScore { get; set; }
    public string BaseCategory { get; set; } = string.Empty;
    public int UnresolvedBlockersCount { get; set; }
    public List<string> BlockerTitles { get; set; } = new();
    public List<string> CatalystTitles { get; set; } = new();
    public List<CrossModuleInvestmentBlockerDto> CrossModuleBlockers { get; set; } = new();
    public bool HasCrossModuleBlockers => CrossModuleBlockers.Count > 0;
    public string SummaryDescription { get; set; } = string.Empty;
}

public class CrossModuleInvestmentBlockerDto
{
    public string ModuleTitle { get; set; } = string.Empty;
    public string SectionId { get; set; } = string.Empty;
    public string FindingCode { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public RiskSeverity Severity { get; set; }
    public string WhyItBlocksDueDiligence { get; set; } = string.Empty;
}

public class UnifiedActionItemDto
{
    public int Number { get; set; }
    public string ActionId { get; set; } = string.Empty;
    public string ActionType { get; set; } = "LEGAL_WORK";
    public ResolutionMode ResolutionMode { get; set; } = ResolutionMode.LegalWork;
    public RiskPriority Priority { get; set; }
    public string PriorityGroup { get; set; } = "В ПЕРВУЮ ОЧЕРЕДЬ"; // В ПЕРВУЮ ОЧЕРЕДЬ, СЛЕДУЮЩИМ ЭТАПОМ, ДО РАУНДА / СДЕЛКИ, ПОЗЖЕ
    public string Title { get; set; } = string.Empty;
    public string WhatToDo { get; set; } = string.Empty;
    public string WhyNow { get; set; } = string.Empty;
    public string ExpectedResult { get; set; } = string.Empty;
    public string ResolutionFormat { get; set; } = "Требуется юридическая работа";
    public List<string> Dependencies { get; set; } = new();
    public List<string> CoveredFindingCodes { get; set; } = new();
    public List<string> CoveredFindingIds => CoveredFindingCodes;
}

public class FenixLawRecommendationReportDto
{
    public bool RequiresLegalWork { get; set; }
    public string SummaryText { get; set; } = string.Empty;
    public List<string> ServiceAreas { get; set; } = new();
    public List<FenixLawServiceCardDto> ServiceCards { get; set; } = new();
    public string CtaTitle { get; set; } = "Связаться с Fenix Law";
    public string CtaSubtext { get; set; } = "Для обсуждения устранения выявленных рисков и индивидуального юридического сопровождения:";
    public string Telegram { get; set; } = "@fenixlaw";
    public string Website { get; set; } = "www.fenixlaw.org";
    public string Phone { get; set; } = "+7-700-559-1377";
    public string Email { get; set; } = "team@fenixlaw.org";
}

public class FenixLawServiceCardDto
{
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string? Icon { get; set; }
}

public class MethodologyAndDisclaimerDto
{
    public string MethodologyText { get; set; } = string.Empty;
    public string DisclaimerText { get; set; } = string.Empty;
}
